import { ref, set } from "firebase/database";
import { database } from "./firebase.mjs";

set(ref(database, `reviews`), {
    review1: {
      reviewerId: "cust1",
      reviewerType: "customer",
      reviewerName: "John Doe",
      reviewedUserId: "prov1",
      reviewedUserType: "provider",
      reviewedUserName: "Elegant Grooming",
      serviceId: "serv1",
      serviceName: "Haircut",
      rating: 5,
      comment: "Excellent service! The provider was very professional.",
      timestamp: 1708735200000,
    },
    review2: {
      reviewerId: "prov2",
      reviewerType: "provider",
      reviewerName: "Clean Cuts Salon",
      reviewedUserId: "cust2",
      reviewedUserType: "customer",
      reviewedUserName: "Emily Johnson",
      serviceId: "",
      serviceName: "",
      rating: 4,
      comment: "Customer was pleasant to work with and punctual.",
      timestamp: 1708745200000,
    },
    review3: {
      reviewerId: "cust3",
      reviewerType: "customer",
      reviewerName: "Michael Clark",
      reviewedUserId: "prov3",
      reviewedUserType: "provider",
      reviewedUserName: "Luxury Manicure",
      serviceId: "serv3",
      serviceName: "Manicure",
      rating: 3,
      comment: "Service was okay, but the tools seemed unclean.",
      timestamp: 1708755200000,
    },
    review4: {
      reviewerId: "cust4",
      reviewerType: "customer",
      reviewerName: "Sara Evans",
      reviewedUserId: "prov4",
      reviewedUserType: "provider",
      reviewedUserName: "Pampered Pedicures",
      serviceId: "serv4",
      serviceName: "Pedicure",
      rating: 5,
      comment: "Fantastic experience! Highly recommend.",
      timestamp: 1708765200000,
    },
    review5: {
      reviewerId: "prov5",
      reviewerType: "provider",
      reviewerName: "Glamour Styles",
      reviewedUserId: "cust5",
      reviewedUserType: "customer",
      reviewedUserName: "David Wilson",
      serviceId: "",
      serviceName: "",
      rating: 2,
      comment: "Customer was late and uncooperative.",
      timestamp: 1708775200000,
    },
    review6: {
      reviewerId: "cust6",
      reviewerType: "customer",
      reviewerName: "Jessica Brown",
      reviewedUserId: "prov6",
      reviewedUserType: "provider",
      reviewedUserName: "Barber's Corner",
      serviceId: "serv6",
      serviceName: "Haircut",
      rating: 4,
      comment: "Great service, but the wait time was too long.",
      timestamp: 1708785200000,
    },  });
